"""baselines and detector allowlist

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-08 09:37:30.669588

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "baseline_definitions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("timeline_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("baseline_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("baseline_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("suspect_windows", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_baseline_definitions_case_id"), "baseline_definitions", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_baseline_definitions_timeline_id"),
        "baseline_definitions",
        ["timeline_id"],
        unique=False,
    )
    op.create_table(
        "detector_allowlist",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("timeline_id", sa.String(length=64), nullable=False),
        sa.Column("detector", sa.String(length=32), nullable=False),
        sa.Column("field", sa.String(length=255), nullable=False),
        sa.Column("value", sa.String(length=4096), nullable=False),
        sa.Column("note", sa.String(length=4096), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_detector_allowlist_case_id"), "detector_allowlist", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_detector_allowlist_timeline_id"),
        "detector_allowlist",
        ["timeline_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_detector_allowlist_timeline_id"), table_name="detector_allowlist")
    op.drop_index(op.f("ix_detector_allowlist_case_id"), table_name="detector_allowlist")
    op.drop_table("detector_allowlist")
    op.drop_index(op.f("ix_baseline_definitions_timeline_id"), table_name="baseline_definitions")
    op.drop_index(op.f("ix_baseline_definitions_case_id"), table_name="baseline_definitions")
    op.drop_table("baseline_definitions")
    # ### end Alembic commands ###
